# Shell variables
# Generated by 'wal'
wallpaper='/home/nya/Downloads/3f461bppquy21.png'

# Special
background='#101239'
foreground='#f2c1c5'
cursor='#f2c1c5'

# Colors
color0='#101239'
color1='#C05A7F'
color2='#A13C83'
color3='#C73585'
color4='#B04887'
color5='#D95492'
color6='#F26F9A'
color7='#f2c1c5'
color8='#a98789'
color9='#C05A7F'
color10='#A13C83'
color11='#C73585'
color12='#B04887'
color13='#D95492'
color14='#F26F9A'
color15='#f2c1c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
