--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/nya/Downloads/3f461bppquy21.png"

-- Special
background="#101239"
foreground="#f2c1c5"
cursor="#f2c1c5"

-- Colors
color0="#101239"
color1="#C05A7F"
color2="#A13C83"
color3="#C73585"
color4="#B04887"
color5="#D95492"
color6="#F26F9A"
color7="#f2c1c5"
color8="#a98789"
color9="#C05A7F"
color10="#A13C83"
color11="#C73585"
color12="#B04887"
color13="#D95492"
color14="#F26F9A"
color15="#f2c1c5"
